/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.gui;

import project.Controller;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 *
 * @author Rich
 */
public final class AccountHolderFrame extends AbstractUserWindow {

    /**
     * Creates new form AccountHolderFrame
     */
    private Set<project.gui.AccountTab> accountTabs = new HashSet<project.gui.AccountTab>();

    public AccountHolderFrame(Controller controller){
        super(controller);
        initComponents();
        setSummaryTableModel();
        buildAccountTabs();
    }
    
    private void setSummaryTableModel() {
        SummaryTable.setModel(new javax.swing.table.DefaultTableModel(
                controller.updateAccountHolderTableView(),
                new String[]{
            "Account Type", "Account Number", "Balance"
        }) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        SummaryTable.revalidate();
    }

    private void buildAccountTabs() {
        accountTabs.clear();
        List<project.gui.AccountTab> accTabList = controller.getTabs(this);
        for (project.gui.AccountTab accTab : accTabList) {
            accountTabs.add(accTab);
            AccountHolderTabs.add(accTab);
        }
        AccountHolderTabs.revalidate();
    }
    
    @Override
    public void logout(){
        super.logout();
        controller.getTabs(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountHolderTabs = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SummaryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocationByPlatform(true);
        setName(""); // NOI18N

        HomePanel.setAutoscrolls(true);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Accounts Summary");

        jScrollPane1.setViewportView(SummaryTable);

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
                .addContainerGap())
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        AccountHolderTabs.addTab("HOME", HomePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountHolderTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountHolderTabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AccountHolderTabs;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JTable SummaryTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
