/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.gui;

import project.Controller;
import project.model.Bank;
import project.model.InvalidInputException;
import project.model.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 * @author Rich
 */
public final class LoginWindow extends javax.swing.JFrame {
    /**
     * Creates new form LoginWindow
     */
    private Controller controller;
    private Frame parent;
    private final String[] userString = new String[]{"Account Holder", "Account Manager", "Accountant", "Auditor", "Operations Manager", "Teller"};

    /**
     * @param title      The title on the Window
     * @param controller The controller
     */
    public LoginWindow(String title, final Controller controller) {
        setTitle(title);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.controller = controller;
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                controller.shutDown();
            }
        });
    }

    public void confirmTellerLogin() {
        // TODO figure out what this does
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        employeeCheckBox = new JCheckBox();
        EmployeeLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("USER LOGIN");
        setLocationByPlatform(true);
        setResizable(false);

        UsernameLabel.setText("Username:");

        LoginButton.setText("LOGIN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        EmployeeLabel.setText("Login as an Employee?");

        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(UsernameLabel)
                                        .addComponent(username)
                                        .addComponent(EmployeeLabel)
                                        .addComponent(employeeCheckBox, 0, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LoginButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(UsernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EmployeeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(employeeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LoginButton))
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        User user;
        //Make sure the User exsists
        try {
            user = Bank.getInstance().getUser(username.getText());
        } catch (InvalidInputException ex) {
            controller.handleException(this, ex);
            return;
        }

        boolean loginAsEmployee = employeeCheckBox.isSelected();
        // make sure the user has the correct credentials
        if (loginAsEmployee && user.getRole() == null) {
            JOptionPane.showMessageDialog(this, "You are not an employee; you cannot log in as one.", "Login error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!loginAsEmployee && !user.isActiveCustomer()) {
            JOptionPane.showMessageDialog(this, "You have no active accounts, so you cannot log in as a customer.", "Login error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Closes itself and opens the appropriate Frame through the Controller
        this.dispose();
        controller.newAbstractUserWindow(user);

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            LoginButtonActionPerformed(null);
        }
    }//GEN-LAST:event_usernameKeyPressed

    private void UserComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserComboBoxKeyPressed
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            LoginButtonActionPerformed(null);
        }
    }//GEN-LAST:event_UserComboBoxKeyPressed

    // TODO I modified this
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JCheckBox employeeCheckBox;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
