/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.gui;

import project.Controller;
import project.model.InvalidInputException;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Rich
 */
public class TellerFrame extends AbstractUserWindow {

    
    List<TellerAccountTab> tabs = new ArrayList<TellerAccountTab>();
    
    /**
     * Creates new form TellerFrame
     */
    public TellerFrame(Controller controller) {
        super(controller);
        initComponents();
    }
    
    private void setUpTabs(){
        for(TellerAccountTab tab : tabs){
            TellerTabHolder.add(tab);
            TellerTabHolder.revalidate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TellerTabHolder = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        usernameField = new javax.swing.JFormattedTextField();
        selectUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectUserButton.setText("Select");
        selectUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectUserButton)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectUserButton))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        TellerTabHolder.addTab("Home", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TellerTabHolder)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TellerTabHolder)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserButtonActionPerformed
        try {
            tabs = controller.getTellerTabs(controller.getInstance().getUser(usernameField.getText()));
            setUpTabs();
        } catch (InvalidInputException ex) {
            controller.handleException(this, ex);
        }
    }//GEN-LAST:event_selectUserButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TellerTabHolder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selectUserButton;
    private javax.swing.JFormattedTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
