/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.gui;

import java.awt.event.KeyEvent;
import project.Controller;
import project.model.InvalidInputException;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import project.model.User;

/**
 *
 * @author Rich
 */
public class TellerFrame extends AbstractUserWindow {

    List<TellerAccountTab> tabs = new ArrayList<TellerAccountTab>();

    /**
     * Creates new form TellerFrame
     */
    public TellerFrame(Controller controller) {
        super(controller);
        initComponents();
        usernameField.selectAll();
        usernameField.requestFocusInWindow();
    }

    private void setUpTabs() {
        for (TellerAccountTab tab : tabs) {
            TellerTabHolder.add(tab);
            TellerTabHolder.revalidate();
        }
    }
    
    private void removeTabs() {
        for (TellerAccountTab tab : tabs) {
            TellerTabHolder.remove(tab);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TellerTabHolder = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        usernameField = new javax.swing.JFormattedTextField();
        selectUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        TellerTabHolder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TellerTabHolderStateChanged(evt);
            }
        });

        usernameField.setText("Username");
        usernameField.setToolTipText("Enter a Customer's username");
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });
        usernameField.requestFocusInWindow();

        selectUserButton.setText("New Customer");
        selectUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserButtonActionPerformed(evt);
            }
        });
        selectUserButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                selectUserButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectUserButton)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectUserButton))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        TellerTabHolder.addTab("Home", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TellerTabHolder)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TellerTabHolder)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserButtonActionPerformed
        try {
            User user = controller.getInstance().getUser(usernameField.getText());
            removeTabs();
            tabs = controller.getTellerTabs(user);
            setUpTabs();
        } catch (InvalidInputException ex) {
            controller.handleException(this, ex);
        }
    }//GEN-LAST:event_selectUserButtonActionPerformed

    private void TellerTabHolderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TellerTabHolderStateChanged
        if (TellerTabHolder.getSelectedIndex() > 0) {
            TellerAccountTab tab = (TellerAccountTab) TellerTabHolder.getSelectedComponent();
            if (!tab.isFeeIncurred()) {
                if (JOptionPane.showConfirmDialog(this, ("Do you want to waive fees for transactions on this account?")) != JOptionPane.YES_OPTION) {
                    tab.incurFee();
                }
                tab.waiveFee();
            }
        }
    }//GEN-LAST:event_TellerTabHolderStateChanged

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyPressed
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            selectUserButton.doClick();
        }
    }//GEN-LAST:event_usernameFieldKeyPressed

    private void selectUserButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectUserButtonKeyPressed
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            selectUserButton.doClick();
        }
    }//GEN-LAST:event_selectUserButtonKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TellerTabHolder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selectUserButton;
    private javax.swing.JFormattedTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
